server:
  port: ${ENV_SERVER_PORT:8082}

spring:
  application:
    name: programa-service

  profiles:
    active: ${ENV_SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  config:
    import: "optional:configserver:${ENV_CONFIG_SERVER_URL:http://config-server:8888}"


